#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if yarn is installed, otherwise fall back to npm
if command -v yarn >/dev/null 2>&1; then
    echo "Running formatter using yarn..."
    yarn format
    echo "Staging formatted files..."
    git add .
else
    echo "Yarn not found, falling back to npm..."
    npm run format
    echo "Staging formatted files..."
    git add .
fi
