#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check if yarn is installed, otherwise fall back to npm
if command -v yarn >/dev/null 2>&1; then
    echo "Running formatter using yarn..."
    yarn format
    echo "Re-staging only previously staged files..."
    git update-index --again
else
    echo "Yarn not found, falling back to npm..."
    npm run format
    echo "Re-staging only previously staged files..."
    git update-index --again
fi
